title: Mohammad Ahmadi Sadr
logo: "/images/profile.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Android Developer<br>
  Contact:<br>
    <a href="tel:+14384540470"> +1 438 454 0470</a><br>
    <a href="mailto:mohamadahmadisadr@gmail.com"> mohamadahmadisadr@gmail.com</a>
    <a href="https://www.linkedin.com/in/mohamadahmadisadr/">Linkedin</a><br>
    <a href="https://www.github.com/mohamadahmadisadr/">github</a>

plugins:
- jekyll-feed
- jekyll-seo-tag
google_analytics: G-XHJ4S9BBFE
